name: Get-Samples
on:
  workflow_dispatch:
    inputs:
      search_query:
        description: "Search Query in format 'term'+'term'..."
        required: true
        default: "loop"

jobs:
  get-samples:
    name: ""
    runs-on: ubuntu-latest
    env:
      GOOGLE_DRIVE_CLIENT_EMAIL: ${{ secrets.GOOGLE_DRIVE_CLIENT_EMAIL }}
      GOOGLE_DRIVE_PRIVATE_KEY: ${{ secrets.GOOGLE_DRIVE_PRIVATE_KEY }}
      GOOGLE_DRIVE_UPLOAD_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_UPLOAD_FOLDER_ID }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - run: |
          yarn
          echo "Searching Samples for Search Query: ${{ github.event.inputs.search_query }}"
          node src/get-samples.js ${{ github.event.inputs.search_query }}
