name: Get-Samples
on:
  workflow_dispatch:
    inputs:
      search_query:
        description: "Search Query in format 'term'+'term'..."
        required: true
        default: "loop"

jobs:
  collecting-samples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - run: |
          yarn
          echo "Searching Samples for Search Query: ${{ github.event.inputs.search_query }}"
          export TEST_TOKEN=${{ secrets.TEST_TOKEN }}
          node src/get-samples.js ${{ github.event.inputs.search_query }}
